### ISSUE TITLE
Motivation Question

### ISSUE THREAD

**Issue by born2defy** [coot/purescript-react-spaces#4]
Hey there - very nice library.  I am curious what your motivation for writing it was, as compared to using the PUX library.  It seems that both approaches will suffer from the same overhead issues of having to interpret the Free Monad on every render.

**Comment by coot** [comment]
I just wanted to have a solution that you can plug into react without using pux.  Indeed it suffers from the overhead of the free monad.  I was thinking about writing a tool that could optimise it. That shouldn't be too difficult using purescript's corefn representation.

**Comment by born2defy** [comment]
Interesting.  I'm curious what your optimization approach would be as I have been thinking along the same lines but haven't isolated a good strategy yet.

**Comment by coot** [comment]
That could be a series of different optimisations,like detecting appplicative parts, inlining, etc.
